editoggia/models/story.py
# models.py ---
#
# Filename: models.py
# Author: Louise <louise>
# Created: Thu May 14 18:25:31 2020 (+0200)
# Last-Updated: Fri Jul 17 03:57:24 2020 (+0200)
#           By: Louise <louise>
#
"""
The models for the story blueprint.
"""
from flask_babelex import gettext

from editoggia.database import db
from editoggia.models.mixins import CRUDMixin, DatesMixin, PKMixin


class Story(db.Model, CRUDMixin, DatesMixin):
    """
    A story, written on the site.
    """

    __tablename__ = "story"

    title = db.Column(db.String(255), nullable=False, index=True)
    summary = db.Column(db.String(1000), nullable=False, default="")
    total_chapters = db.Column(db.Integer())

    rating = db.Column(
        db.Enum(
            gettext("General audiences"),
            gettext("Teen and up audiences"),
            gettext("Mature"),
            gettext("Explicit"),
            name="enum_rating",
        )
    )

    fandom = db.relationship(
        "Fandom", secondary="fandom_stories", back_populates="stories"
    )

    stats_id = db.Column(db.Integer(), db.ForeignKey("storystats.id"), nullable=False)
    stats = db.relationship("StoryStats", back_populates="story")

    author_id = db.Column(db.Integer(), db.ForeignKey("user.id"), nullable=False)
    author = db.relationship("User", back_populates="stories")

    chapters = db.relationship(
        "Chapter",
        back_populates="story",
        cascade="all, delete, delete-orphan",
        order_by="Chapter.nb",
    )
    tags = db.relationship("Tag", secondary="story_tags", back_populates="stories")

    user_likes = db.relationship("User", secondary="user_likes", back_populates="likes")

    shelves = db.relationship(
        "Shelf", secondary="shelves_stories", back_populates="stories"
    )

    @classmethod
    def create(cls, commit=True, **kwargs):
        """
        We overload the create method to create automatically
        the Story and the StoryStats object.
        """
        stats = StoryStats()
        story = Story(stats=stats, **kwargs)

        return story.save()

    def hit(self):
        """
        If user is not the author, increment hit.
        Should only be called once per registrated
        user.
        """
        from flask_login import current_user

        if current_user != self.author:
            self.stats.hits += 1
            db.session.commit()

    def keywords(self):
        """
        Returns fandoms and tags as a string, comma-separated.
        """
        return ", ".join(map(lambda obj: obj.name, self.fandom + self.tags))

    def __setattr__(self, attr, value):
        """
        We overload this method to allow for special behaviour
        for the fandom and tag fields. Hereby, we can set their
        fields with strings and actually set the objects.
        """
        from editoggia.models.fandom import Fandom
        from editoggia.models.tag import Tag

        # The second check checks that the first element in the
        # list exists, and that it's a string. If there is no
        # first element, or if the value is already a model,
        # we have no need for the transformation.
        if attr == "fandom" and type(next(iter(value), 0)) == str:
            value = [Fandom.get_or_create(fandom) for fandom in value]
        if attr == "tags" and type(next(iter(value), 0)) == str:
            value = [Tag.get_or_create(tag) for tag in value]

        super().__setattr__(attr, value)

    def __repr__(self):
        return "<Story '{}', by '{}'>".format(self.title, self.author)


class StoryStats(db.Model, PKMixin):
    __tablename__ = "storystats"

    hits = db.Column(db.Integer(), nullable=False, default=0)
    story = db.relationship("Story", back_populates="stats")


class Chapter(db.Model, CRUDMixin, DatesMixin):
    """
    A chapter. Simple as that.
    """

    __tablename__ = "chapter"
    __table_args__ = (
        # There can only be one chapter with a certain number by
        # story ID.
        db.UniqueConstraint("nb", "story_id", name="unique_chapter_nb"),
    )

    nb = db.Column(db.Integer(), nullable=False, index=True)

    title = db.Column(db.String(255), nullable=False, default="")
    summary = db.Column(db.Text())
    content = db.Column(db.Text(), nullable=False)

    comments = db.relationship("Comment", back_populates="chapter")

    story_id = db.Column(db.Integer(), db.ForeignKey("story.id"), nullable=False)
    story = db.relationship("Story", back_populates="chapters")

    def __repr__(self):
        return "<Chapter {} of story '{}', by '{}'>".format(
            self.nb, self.story.title, self.story.author
        )

editoggia/story/__init__.py
# __init__.py ---
#
# Filename: __init__.py
# Author: Louise <louise>
# Created: Thu May 14 18:24:27 2020 (+0200)
# Last-Updated: Mon Jun  8 15:30:38 2020 (+0200)
#           By: Louise <louise>
#
"""
The blueprint managing the story aspect of the website.
Stories, fandoms, chapters, and the like.
"""
from flask import Blueprint

story = Blueprint("story", __name__)

import editoggia.story.admin  # noqa
import editoggia.story.views  # noqa

editoggia/story/views.py
# views.py --- 
# 
# Filename: views.py
# Author: Louise <louise>
# Created: Thu May 14 18:26:12 2020 (+0200)
# Last-Updated: Mon Jun  8 15:17:30 2020 (+0200)
#           By: Louise <louise>
#
from flask import render_template, redirect, url_for

from editoggia.database import db
from editoggia.story import story

from editoggia.models import Story, Chapter

@story.route('/')
def index():
    """
    Show the index of all stories
    """
    stories = db.session.query(Story).order_by(Story.updated_on.desc()).all()
    
    return render_template("story/index.jinja2", stories=stories)
    
@story.route('/<int:story_id>')
def show_story(story_id):
    """
    Show a story. In practice, redirect to the first chapter if there
    is multiple, and else render the only chapter.
    """
    story = Story.get_by_id_or_404(story_id)
    
    if len(story.chapters) > 1:
        return redirect(url_for('story.show_chapter',
                                story_id=story_id,
                                chapter_id=story.chapters[0].id)
        )
    else:
        story.hit()
        return render_template('story/show_chapter.jinja2',
                               story=story,
                               chapter=story.chapters[0])

@story.route('/<int:story_id>/chapter/<chapter_id>')
def show_chapter(story_id, chapter_id):
    """
    Show a chapter.
    """
    story = Story.get_by_id_or_404(story_id)
    chapter = Chapter.get_by_id_or_404(chapter_id)

    story.hit()
    
    return render_template('story/show_chapter.jinja2',
                           story=story,
                           chapter=chapter)

@story.route('/<int:story_id>/index')
def story_index(story_id):
    """
    Show the index of a particular story.
    """
    story = Story.get_by_id_or_404(story_id)

    return render_template('story/story_index.jinja2', story=story)

editoggia/story/views/__init__.py
# __init__.py ---
#
# Filename: __init__.py
# Author: Louise <louise>
# Created: Mon Jun  8 15:30:42 2020 (+0200)
# Last-Updated: Sat Jun 27 14:31:28 2020 (+0200)
#           By: Louise <louise>
#
import editoggia.story.views.edit  # noqa
import editoggia.story.views.interaction  # noqa
import editoggia.story.views.post  # noqa
import editoggia.story.views.view  # noqa

editoggia/story/views/edit.py
# edit_views.py ---
#
# Filename: edit_views.py
# Author: Louise <louise>
# Created: Mon Jun  8 15:10:40 2020 (+0200)
# Last-Updated: Sun Jul 12 00:28:27 2020 (+0200)
#           By: Louise <louise>
#
"""
Views for editing content (stories and chapters)
"""
from flask import abort, redirect, render_template, url_for
from flask_login import current_user, login_required

from editoggia.bleacher import bleach
from editoggia.models import Chapter, Story
from editoggia.story import story
from editoggia.story.forms import ChapterForm, EditStoryForm


@story.route("/edit/<int:story_id>", methods=["GET", "POST"])
@login_required
def edit_story(story_id):
    """
    Edit a story.
    """
    # The story has to exist and to have been written by the
    # current user
    story = Story.get_by_id_or_404(story_id)
    if story.author != current_user:
        abort(403)

    form = EditStoryForm(obj=story)

    if form.validate_on_submit():
        # Bleach summary
        form.summary.process_data(bleach(form.data["summary"]))

        # We update the story
        form.populate_obj(story)
        story.update()

        return redirect(url_for("home.index"))

    form.populate_select2(story.fandom, story.tags)
    return render_template("story/edit_story.jinja2", form=form, story=story)


@story.route("/edit/<int:story_id>/chapter/<int:chapter_id>", methods=["GET", "POST"])
@login_required
def edit_chapter(story_id, chapter_id):
    """
    Edit a chapter
    """
    # The story has to exist and to have been written by the
    # current user
    chapter = Chapter.get_by_id_or_404(chapter_id)
    if chapter.story.author != current_user:
        abort(403)

    form = ChapterForm(obj=chapter, chapter=chapter, story=chapter.story)

    if form.validate_on_submit():
        form.content.process_data(bleach(form.data["content"]))
        form.summary.process_data(bleach(form.data["summary"]))

        form.populate_obj(chapter)
        chapter.update()

        return redirect(url_for("story.edit_story", story_id=story_id))

    return render_template("story/edit_chapter.jinja2", form=form, chapter=chapter)

editoggia/story/views/interaction.py
# interaction.py ---
#
# Filename: interaction.py
# Author: Louise <louise>
# Created: Sat Jun 27 13:58:01 2020 (+0200)
# Last-Updated: Sat Jul 11 04:02:29 2020 (+0200)
#           By: Louise <louise>
#
"""
This file defines views for interaction, such as like, or comment.
"""
from flask import abort, redirect, url_for
from flask_login import current_user, login_required

from editoggia.bleacher import bleach
from editoggia.database import db
from editoggia.models import Chapter, Comment, Story
from editoggia.story import story
from editoggia.story.forms import CommentForm, LikeForm


@story.route("/<int:story_id>/like", methods=["POST"])
@login_required
def like(story_id):
    """
    Like or unlike a story. Can only be accessed by POST.
    """
    form = LikeForm()
    story = Story.get_by_id_or_404(story_id)

    if form.validate_on_submit():
        # If the story is not already liked, like it
        # Else, remove it from the likes.
        if story not in current_user.likes:
            current_user.likes.append(story)
        else:
            current_user.likes.remove(story)

        db.session.commit()
        return "", 200

    # If form (and by that we mean CSRF protection) is not right, return 400.
    return "", 400


@story.route("/<int:story_id>/chapter/<int:chapter_id>/comment", methods=["POST"])
@login_required
def comment(story_id, chapter_id):  # pylint: disable=inconsistent-return-statements
    """
    Comment on a chapter. Can only POST too.
    We disable inconsistent lint because abort never
    returns.
    """
    form = CommentForm()
    chapter = Chapter.get_by_id_or_404(chapter_id)

    if form.validate_on_submit():
        content = bleach(form.data["comment"])

        Comment.create(content=content, author=current_user, chapter=chapter)
        return redirect(
            url_for("story.show_chapter", story_id=story_id, chapter_id=chapter_id)
        )

    abort(400)

editoggia/story/views/post.py
# post_views.py ---
#
# Filename: post_views.py
# Author: Louise <louise>
# Created: Mon Jun  8 15:08:41 2020 (+0200)
# Last-Updated: Sun Jul 12 00:28:02 2020 (+0200)
#           By: Louise <louise>
#
"""
Views for posting new content (stories and chapters)
"""
from flask import redirect, render_template, url_for
from flask_login import current_user, login_required

from editoggia.bleacher import bleach
from editoggia.models import Chapter, Story
from editoggia.story import story
from editoggia.story.forms import ChapterForm, PostStoryForm


@story.route("/post", methods=["GET", "POST"])
@login_required
def post_story():
    """
    Post a new story.
    """
    form = PostStoryForm()

    if form.validate_on_submit():
        # First we have to bleach the HTML content we got
        summary = bleach(form.data["summary"])
        content = bleach(form.data["content"])

        # We have to create the story before the chapter
        story = Story.create(
            title=form.data["title"],
            rating=form.data["rating"],
            author=current_user,
            summary=summary,
            fandom=form.data["fandom"],
            tags=form.data["tags"],
            total_chapters=form.data["total_chapters"],
        )

        # Then we create the first chapter
        Chapter.create(
            nb=1, title=form.data["chapter_title"], content=content, story=story
        )

        return redirect(url_for("home.index"))

    form.populate_select2()
    return render_template("story/post_story.jinja2", form=form)


@story.route("/post/<int:story_id>/chapter", methods=["GET", "POST"])
@login_required
def post_chapter(story_id):
    """
    Post a new chapter.
    """
    story = Story.get_by_id_or_404(story_id)
    form = ChapterForm(story=story)

    if form.validate_on_submit():
        # First we have to bleach the HTML content we got
        content = bleach(form.data["content"])
        summary = bleach(form.data["summary"])

        Chapter.create(
            story=story,
            title=form.data["title"],
            nb=form.data["nb"],
            summary=summary,
            content=content,
        )

        # Update story to refresh update time
        story.touch()

        return redirect(url_for("story.edit_story", story_id=story_id))

    # If we get to this point we should return the form
    # Set a default chapter number (Last chapter + 1)
    form.nb.process_data(story.chapters[-1].nb + 1)

    return render_template("story/post_chapter.jinja2", story=story, form=form)

editoggia/story/views/view.py
# views.py ---
#
# Filename: views.py
# Author: Louise <louise>
# Created: Thu May 14 18:26:12 2020 (+0200)
# Last-Updated: Wed Feb 10 14:09:45 2021 (+0100)
#           By: Louise <louise>
#
"""
Views for viewing stories and chapters.
"""
from flask import redirect, render_template, url_for
from flask_login import current_user

from editoggia.database import db
from editoggia.models import Chapter, Story
from editoggia.story import story
from editoggia.story.forms import CommentForm, LikeForm


@story.route("/")
def index():
    """
    Show the last 20 stories.
    """
    stories = db.session.query(Story).order_by(Story.updated_on.desc()).limit(20).all()

    return render_template("story/index.jinja2", stories=stories)


@story.route("/<int:story_id>")
def show_story(story_id):
    """
    Show a story. In practice, redirect to a chapter if there
    is multiple, and else render the only chapter.
    """
    story = Story.get_by_id_or_404(story_id)

    if len(story.chapters) > 1:
        # If story has multiple chapters, restore the progression of the
        # user.
        history = current_user.get_from_history(story)

        if history is None:
            # If we have no history, redirect to the first chapter.
            return redirect(
                url_for(
                    "story.show_chapter",
                    story_id=story_id,
                    chapter_id=story.chapters[0].id,
                )
            )

        return redirect(
            url_for(
                "story.show_chapter",
                story_id=story_id,
                chapter_id=story.chapters[history.chapter_nb - 1].id,
            )
        )

    # If we get to this point, we just load the first chapter since it's a
    # 1-chapter story.
    like_form = LikeForm()
    comment_form = CommentForm()

    current_user.add_to_history(story)
    return render_template(
        "story/show_chapter.jinja2",
        like_form=like_form,
        comment_form=comment_form,
        story=story,
        chapter=story.chapters[0],
    )


@story.route("/<int:story_id>/full")
def show_full_story(story_id):
    """
    Show a full story.
    """
    story = Story.get_by_id_or_404(story_id)

    current_user.add_to_history(story)
    return render_template("story/show_full_story.jinja2", story=story)


@story.route("/<int:story_id>/chapter/<chapter_id>")
def show_chapter(story_id, chapter_id):
    """
    Show a chapter.
    """
    story = Story.get_by_id_or_404(story_id)
    chapter = Chapter.get_by_id_or_404(chapter_id)

    like_form = LikeForm()
    comment_form = CommentForm()

    current_user.add_to_history(story, chapter.nb)
    return render_template(
        "story/show_chapter.jinja2",
        like_form=like_form,
        comment_form=comment_form,
        story=story,
        chapter=chapter,
    )


@story.route("/<int:story_id>/index")
def story_index(story_id):
    """
    Show the index of a particular story.
    """
    story = Story.get_by_id_or_404(story_id)

    return render_template("story/story_index.jinja2", story=story)

editoggia/templates/story/edit_chapter.jinja2
{% from 'components/field.jinja2' import render_field %}
{% extends 'base.jinja2' %}

{% block title %} {{ _("Edit chapter") }} {% endblock %}

{% block content %}
  <section class="section">
    <div class="container">
      <div class="row justify-content-center">
	<div class="col-lg-10">
	  <h2> {{ _("Edit chapter") }} </h2>
	  <form action="{{ url_for('story.edit_chapter', story_id=chapter.story.id, chapter_id=chapter.id) }}" method="POST">
	    {{ form.csrf_token }}
	    <div class="row">
	      {{ render_field(form.title, col="col-lg-10") }}
	      {{ render_field(form.nb, col="col-lg-2") }}
	    </div>
	    <div class="row">
	      {{ render_field(form.summary, rows=5) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.content, rows=20) }}
	    </div>
	    <div class="row pt-2">
	      <div class="form-group col-lg-12">
		<button type="submit" class="btn btn-primary btn-block">{{ _("Submit") }}</button>
	      </div>
	    </div>
	  </form>
	</div>
      </div>
    </div>
  </section>
{% endblock %}

editoggia/templates/story/edit_story.jinja2
{% from 'components/field.jinja2' import render_field %}
{% extends 'base.jinja2' %}

{% block title %} {{ _("Edit story") }} {% endblock %}

{% block content %}
  <section class="section">
    <div class="container">
      <div class="row justify-content-center">
	<div class="col-lg-7">
	  <h2> {{ _("Edit story") }} </h2>
	  <form action="{{ url_for('story.edit_story', story_id=story.id) }}" method="POST">
	    {{ form.csrf_token }}
	    <div class="row">
	      {{ render_field(form.title) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.rating, 'col-lg-9') }}
	      {{ render_field(form.total_chapters, 'col-lg-3') }}
	    </div>
	    <div class="row">
	      {{ render_field(form.summary, rows=5) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.fandom) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.tags) }}
	    </div>
	    <div class="row pt-2">
	      <div class="form-group col-lg-12">
		<button type="submit" class="btn btn-primary btn-block">{{ _("Submit") }}</button>
	      </div>
	    </div>
	  </form>
	</div>
	<div class="col-lg-3">
	  <h2>{{ _("Edit chapters") }}</h2>
	  <div class="list-group list-group-flush">
	    {% for chapter in story.chapters %}
	      <a class="list-group-item list-group-item-action" href="{{ url_for('story.edit_chapter', story_id=story.id, chapter_id=chapter.id) }}">
		{% if chapter.title %}
		  {{ _("Chapter %(chapter_nb)s: %(chapter_title)s", chapter_nb=chapter.nb, chapter_title=chapter.title) }}
		{% else %}
		  {{ _("Chapter %(chapter_nb)s", chapter_nb=chapter.nb) }}
		{% endif %}
	      </a>
	    {% endfor %}
	  </div>
	  <a class="btn btn-block btn-secondary mt-1" href="{{ url_for('story.post_chapter', story_id=story.id) }}">
	    {{ _("Add a chapter") }}
	  </a>
	</div>
      </div>
    </div>
  </section>
{% endblock %}

{% block javascript %}
  {{ super() }}
  {% assets 'js_edit_story' %}
  <script src="{{ ASSET_URL }}"></script>
{% endassets %}
{% endblock %}

editoggia/templates/story/index.jinja2
{% from 'components/story_card.jinja2' import render_story_card with context %}
{% extends 'base.jinja2' %}

{% block title %} {{ _("Story list") }} {% endblock %}

{% block content %}
  <section class="container mt-1" id="main_profile">
    <div class="row">
      <div class="col">
	<h2>{{ _("Recent stories") }}</h2>
	<h6>{{ _("This page only lists the 20 most recent stories. To find more stories, check out directly a fandom or a tag!") }}</h6>
	{% for story in stories %}
	  {{ render_story_card(story) }} 
	{% endfor %}
      </div>
  </section>
{% endblock %}

editoggia/templates/story/post_chapter.jinja2
{% from 'components/field.jinja2' import render_field %}
{% extends 'base.jinja2' %}

{% block title %} {{ _("Post chapter") }} {% endblock %}

{% block content %}
  <section class="section">
    <div class="container">
      <div class="row justify-content-center">
	<div class="col-lg-10">
	  <h2> {{ _("Post chapter") }} </h2>
	  <form action="{{ url_for('story.post_chapter', story_id=story.id) }}" method="POST">
	    {{ form.csrf_token }}
	    <div class="row">
	      {{ render_field(form.title, col="col-lg-10") }}
	      {{ render_field(form.nb, col="col-lg-2") }}
	    </div>
	    <div class="row">
	      {{ render_field(form.summary, rows=5) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.content, rows=20) }}
	    </div>
	    <div class="row pt-2">
	      <div class="form-group col-lg-12">
		<button type="submit" class="btn btn-primary btn-block">{{ _("Submit") }}</button>
	      </div>
	    </div>
	  </form>
	</div>
      </div>
    </div>
  </section>
{% endblock %}

editoggia/templates/story/post_story.jinja2
{% from 'components/field.jinja2' import render_field %}
{% extends 'base.jinja2' %}

{% block title %} {{ _("Post a new story") }} {% endblock %}

{% block content %}
  <section class="section">
    <div class="container">
      <div class="row justify-content-center">
	<div class="col-lg-8 text-justified">
	  <h2 class="title text-center"> {{ _("Post a new story") }} </h2>
	  <form action="{{ url_for('story.post_story') }}" method="POST">
	    {{ form.csrf_token }}
	    <div class="row">
	      {{ render_field(form.title) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.rating) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.summary, rows=5) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.fandom) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.tags) }}
	    </div>
	    <div class="row">
	      <div class="col">
		<input type="checkbox" id="multi-chapter">
		<label for="multi-chapter">{{ _("This story has multiple chapters") }}</label>
	      </div>
	    </div>
	    <div class="editoggia-d-none" id="multi-chapter-reveal">
	      <div class="row">
		{{ render_field(form.chapter_title, "col-lg-9") }}
		{{ render_field(form.total_chapters, "col-lg-3") }}
	      </div>
	    </div>
	    <div class="row">
	      {{ render_field(form.content, rows=20) }}
	    </div>
	    <div class="row pt-2">
	      <div class="form-group col-lg-12">
		<button type="submit" class="btn btn-primary btn-block">{{ _("Submit") }}</button>
	      </div>
	    </div>
	  </form>
	</div>
      </div>
    </div>
  </section>
{% endblock %}

{% block javascript %}
  {{ super() }}
  {% assets 'js_post_story' %}
  <script src="{{ ASSET_URL }}"></script>
{% endassets %}
{% endblock %}

editoggia/templates/story/show_chapter.jinja2
{% from 'components/field.jinja2' import render_field %}
{% from 'components/comment_card.jinja2' import render_comment_card %}
{% extends 'base.jinja2' %}

{% block title %}
  {% if story.chapters|length > 1 %}
    {{ story.title|e }} — {{ _("Chapter") }} {{ chapter.nb }}
  {% else %}
    {{ story.title|e }}
  {% endif %}
{% endblock %}

{% block meta %}
  <meta name="author" content="{{ story.author }}" />
  <meta name="description" content="{{ story.summary }}" />
  <meta name="keywords" content="{{ story.keywords() }}" />
{% endblock %}

{% block content %}
  <section class="container">
    <div class="row justify-content-center">
      <div class="col-lg-9">
	<div class="row mb-3">
	  <div class="col">
	    <h2 class="mx-5 text-center"> {{ story.title }}</h2>
	    <a href="{{ url_for('user.profile', username=story.author.username) }}">
	      <h4 class="text-center"> {{ story.author }} </h4>
	    </a>
	    <hr />
	    {% if story.chapters|length > 1 %}
	      <h4 class="text-center">
		{% if chapter.title %}
		  {{ _("Chapter") }} {{ chapter.nb }} — {{ chapter.title|e }}
		{% else %}
		  {{ _("Chapter") }} {{ chapter.nb }}
		{% endif %}
	      </h4>
	      {% if chapter.summary %}
		<hr />
		<div class="text-center font-italic">{{ _("Summary") }}</div>
		<div id="summary" class="text-justify">{{ chapter.summary }}</div>
		<hr />
	      {% endif %}
	    {% endif %}
	    <div id="story-content" class="text-justify">{{ chapter.content }}</div>
	  </div>
	</div>

	{# Chapter navigation #}
	{% if story.chapters|length > 1 %}
	  <div class="row">
	    <div class="col text-center">
	      {% if chapter.nb != 1 %}
		<a href="{{ url_for('story.show_chapter', story_id=story.id, chapter_id=story.chapters[chapter.nb - 2].id) }}">
		  <i class="fas fa-arrow-left"></i>
		  {{ _("Previous chapter") }}
		</a>
	      {% endif %}
	    </div>
	    <div class="col text-center">
	      <a href="{{ url_for('story.story_index', story_id=story.id) }}">
		{{ _("Chapter index") }}
	      </a>
	    </div>
	    <div class="col text-center">
	      <a href="{{ url_for('story.show_full_story', story_id=story.id) }}">
		<i class="fas fa-book"></i>
		{{ _("Full story") }}
	      </a>
	    </div>
	    <div class="col text-center">
	      {% if chapter.nb != story.chapters|length %}
		<a href="{{ url_for('story.show_chapter', story_id=story.id, chapter_id=story.chapters[chapter.nb].id) }}">
		  {{ _("Next chapter") }}
		  <i class="fas fa-arrow-right"></i>
		</a>
	      {% endif %}
	    </div>
	  </div>
	{% endif %}

	{# Interaction #}
	{% if current_user.is_authenticated %}
	  <div class="row">
	    <div class="col text-center">
	      <form id="like-form" action="{{ url_for('story.like', story_id=story.id) }}" method="POST">
		{{ like_form.csrf_token }}
		
		{# Submit link #}
		<a id="like-button" href="javascript:void(0)">
		  {% if story in current_user.likes %}
		    <i class="fas fa-heart"></i>
		  {% else %}
		    <i class="far fa-heart"></i>
		  {% endif %}
		  {{ _("Like") }}
		</a>
	      </form>
	    </div>
	    <div class="col text-center">
	      <a id="comment-appear" href="javascript:void(0)">
		<i class="fas fa-comment"></i> {{ _("Comment") }}
	      </a>
	    </div>
	  </div>

	  {# Comment form. Appears once the link is clicked. #}
	  <div id="comment-form" class="row mt-2 editoggia-d-none">
	    <div class="col">
	      <form action="{{ url_for('story.comment', story_id=story.id, chapter_id=chapter.id) }}" method="POST">
		{{ comment_form.csrf_token }}
		<div class="row">
		  {{ render_field(comment_form.comment, label=False) }}
		</div>
		
		<div class="d-flex justify-content-end">
		  <button class="btn btn-primary btn-sm" type="submit">{{ _("Submit") }}</button>
		</div>
	      </form>
	    </div>
	  </div>
	{% endif %}
	
	{# Comments #}
	<div class="comments">
	  {% for comment in chapter.comments %}
	    {{ render_comment_card(comment) }}
	  {% endfor %}
	</div>
      </div>
    </div>
  </section>
{% endblock %}

{% block javascript %}
  {{ super() }}
  {% assets 'js_story' %}
  <script src="{{ ASSET_URL }}"></script>
{% endassets %}
{% endblock %}