editoggia/models/fandom.py
# fandom.py ---
#
# Filename: fandom.py
# Author: Louise <louise>
# Created: Sat May 30 15:14:50 2020 (+0200)
# Last-Updated: Wed Jul 22 01:50:29 2020 (+0200)
#           By: Louise <louise>
#
from editoggia.database import db
from editoggia.models.mixins import CRUDMixin, ModeratedMixin, NameMixin


class FandomCategory(db.Model, CRUDMixin, NameMixin):
    """
    Represent a category of fandom, like “Books” and such.
    """

    __tablename__ = "fandomcategory"

    name = db.Column(db.String(100), nullable=False)
    fandoms = db.relationship("Fandom", back_populates="category")

    def __repr__(self):
        return "<FandomCategory '{}'>".format(self.name)


class Fandom(db.Model, ModeratedMixin):
    """
    Represent a fandom.
    """

    __tablename__ = "fandom"

    category_id = db.Column(db.Integer(), db.ForeignKey("fandomcategory.id"))
    category = db.relationship("FandomCategory", back_populates="fandoms")

    stories = db.relationship(
        "Story", secondary="fandom_stories", back_populates="fandom"
    )

    def __repr__(self):
        return "<Fandom '{}'>".format(self.name)


class FandomStories(db.Model):
    """
    An association table, allowing each story to have several fandoms.
    """

    __tablename__ = "fandom_stories"

    id = db.Column(db.Integer(), primary_key=True)
    fandom_id = db.Column(db.Integer(), db.ForeignKey("fandom.id"))
    story_id = db.Column(db.Integer(), db.ForeignKey("story.id"))

editoggia/models/tag.py
# tag.py ---
#
# Filename: tag.py
# Author: Louise <louise>
# Created: Sun Jun  7 12:32:42 2020 (+0200)
# Last-Updated: Wed Jul 22 01:50:46 2020 (+0200)
#           By: Louise <louise>
#

from editoggia.database import db
from editoggia.models.mixins import ModeratedMixin


class Tag(db.Model, ModeratedMixin):
    """
    A tag. I really don't know how else to describe it.
    """

    __tablename__ = "tag"

    stories = db.relationship("Story", secondary="story_tags", back_populates="tags")


class StoryTags(db.Model):
    """
    Association table between Story and Tags.
    """

    __tablename__ = "story_tags"

    id = db.Column(db.Integer(), primary_key=True)
    story_id = db.Column(db.Integer(), db.ForeignKey("story.id"))
    tag_id = db.Column(db.Integer(), db.ForeignKey("tag.id"))

editoggia/moderation/forms.py
# forms.py ---
#
# Filename: forms.py
# Author: Louise <louise>
# Created: Sat Jul 11 21:13:06 2020 (+0200)
# Last-Updated: Sat Jul 11 22:58:17 2020 (+0200)
#           By: Louise <louise>
#
from flask_babelex import gettext
from flask_wtf import FlaskForm
from wtforms.fields import FieldList, FormField, HiddenField, StringField
from wtforms.validators import DataRequired

from editoggia.forms.fields import Select2Field


class FandomForm(FlaskForm):
    """
    A form representing only one fandom in moderation.
    """

    id = HiddenField("fandom_id", validators=[DataRequired()])

    name = StringField(
        gettext("Fandom name"),
        validators=[DataRequired(message=gettext("Fandom name can't be empty."))],
    )

    category = Select2Field(
        gettext("Fandom category"),
        choices=[
            ("Anime", gettext("Anime")),
            ("Books", gettext("Books")),
            ("Cartoons", gettext("Cartoons")),
            ("Movies", gettext("Movies")),
            ("TV Shows", gettext("TV Shows")),
            ("Video games", gettext("Video games")),
            ("Other", gettext("Other")),
        ],
    )


class FandomsForm(FlaskForm):
    """
    A form representing several fandoms.
    """

    fandoms = FieldList(FormField(FandomForm))


class TagForm(FlaskForm):
    """
    A form representing only one tag in moderation.
    """

    id = HiddenField("tag_id", validators=[DataRequired()])

    name = StringField(
        gettext("Tag name"),
        validators=[DataRequired(message=gettext("Tag name can't be empty."))],
    )


class TagsForm(FlaskForm):
    """
    A form representing several tags.
    """

    tags = FieldList(FormField(TagForm))

editoggia/moderation/__init__.py
# __init__.py ---
#
# Filename: __init__.py
# Author: Louise <louise>
# Created: Sat Jul 11 21:12:34 2020 (+0200)
# Last-Updated: Sat Jul 11 21:13:02 2020 (+0200)
#           By: Louise <louise>
#
"""
The blueprint managing the moderation aspect.
"""
from flask import Blueprint

moderation = Blueprint("moderation", __name__)

import editoggia.moderation.views  # noqa

editoggia/moderation/views.py
# views.py ---
#
# Filename: views.py
# Author: Louise <louise>
# Created: Sat Jul 11 21:13:04 2020 (+0200)
# Last-Updated: Sat Jul 11 23:01:52 2020 (+0200)
#           By: Louise <louise>
#
from flask import abort, redirect, render_template, url_for
from flask_login import current_user

from editoggia.database import db
from editoggia.models import Fandom, FandomCategory, Tag
from editoggia.moderation import moderation
from editoggia.moderation.forms import FandomsForm, TagsForm


@moderation.before_request
def check_permission():
    """
    This is executed before every request to check if
    the user has moderation permission. None of the views
    in this blueprint can be accessed without permission.
    """
    if not current_user.has_permission("mod.ACCESS_TAG_INTERFACE"):
        abort(403)


@moderation.route("/")
def index():
    return render_template("moderation/index.jinja2")


@moderation.route("/fandoms", methods=["GET", "POST"])
def fandoms():
    """
    The interface to edit fandoms who are waiting for moderations.
    """
    # Get all fandoms who need moderation
    waiting_fandoms = db.session.query(Fandom).filter(Fandom.waiting_mod).all()

    # Create the form and validate it
    form = FandomsForm()
    if form.validate_on_submit():
        # Now we just have to set the data on all fandoms
        for fandom_form in form.fandoms.entries:
            fandom = Fandom.get_by_id_or_404(fandom_form.data["id"])
            category = FandomCategory.get_by_name_or_404(fandom_form.data["category"])

            fandom.update(
                name=fandom_form.data["name"], category=category, waiting_mod=False
            )
        return redirect(url_for("moderation.index"))

    # If we only have GET, fill the forms.

    for fandom in waiting_fandoms:
        form.fandoms.append_entry(fandom)

    return render_template("moderation/fandoms.jinja2", form=form)


@moderation.route("/tags", methods=["GET", "POST"])
def tags():
    """
    The interface to edit tags who are waiting for moderations.
    """
    # Get all fandoms who need moderation
    waiting_tags = db.session.query(Tag).filter(Tag.waiting_mod).all()

    # Create the form and validate it
    form = TagsForm()
    if form.validate_on_submit():
        # Now we just have to set the data on all tags
        for tag_form in form.tags.entries:
            tag = Tag.get_by_id_or_404(tag_form.data["id"])

            tag.update(name=tag_form.data["name"], waiting_mod=False)
        return redirect(url_for("moderation.index"))

    # If we only have GET, fill the forms.
    for tag in waiting_tags:
        form.tags.append_entry(tag)

    return render_template("moderation/tags.jinja2", form=form)

editoggia/templates/moderation/fandoms.jinja2
{% from 'components/field.jinja2' import render_field %}
{% extends 'base.jinja2' %}

{% block content %}
  <section class="container">
    <div class="row justify-content-center">
      <div class="col-lg-9">
	<div class="row mb-3">
	  <div class="col">
	    <h2 class="mx-5 text-center"> {{ gettext("Moderation interface") }}</h2>
	    <hr />
	  </div>
	</div>
	<div class="row">
	  <div class="col">
	    <h3>{{ _("Fandoms") }}</h3>
	  </div>
	</div>
	<div class="row mb-2">
	  {% if form.fandoms.entries|length > 0 %}
	    <form method="POST" action="{{ url_for('moderation.fandoms') }}" class="col">
	      <table class="table">
		<tr>
		  <th>{{ _("Fandom name") }}</th>
		  <th>{{ _("Fandom category") }}</th>
		</tr>
		{{ form.csrf_token }}
		{% for fandom in form.fandoms.entries %}
		  <tr>
		    {{ fandom.form.hidden_tag() }}
		    <td>{{ render_field(fandom.form.name, label=False) }}</td>
		    <td>{{ render_field(fandom.form.category, label=False) }}</td>
		  </tr>
		{% endfor %}
	      </table>
	      <div class="row">
		<div class="col">
		  <button type="submit" class="btn btn-block btn-primary">{{ _("Submit") }}</button>
		</div>
	      </div>
	    </form>
	  {% else %}
	    <div class="col">
	      {{ _("There are no entries to be moderated right now.") }}
	    </div>
	  {% endif %}
	</div>
	<div class="row">
	  <div class="col">
	    <a class="btn btn-primary btn-block" href="{{ url_for('moderation.index') }}">{{ _("Return to moderation index.") }}</a>
	  </div>
	</div>
      </div>
    </div>
  </section>
{% endblock %}

editoggia/templates/moderation/index.jinja2
{% from 'components/field.jinja2' import render_field %}
{% extends 'base.jinja2' %}

{% block title %}
  {{ _("Moderation interface") }}
{% endblock %}

{% block content %}
  <section class="container">
    <div class="row justify-content-center">
      <div class="col-lg-9">
	<div class="row mb-3">
	  <div class="col">
	    <h2 class="mx-5 text-center"> {{ gettext("Moderation interface") }}</h2>
	    <hr />
	  </div>
	</div>
	<div class="row">
	  <div class="col">
	    <a href="{{ url_for('moderation.fandoms') }}">{{ _("Moderate fandoms") }}</a>
	  </div>
	  <div class="col">
	    <a href="{{ url_for('moderation.tags') }}">{{ _("Moderate tags") }}</a>
	  </div>
	</div>
      </div>
    </div>
  </section>
{% endblock %}

editoggia/templates/moderation/tags.jinja2
{% from 'components/field.jinja2' import render_field %}
{% extends 'base.jinja2' %}

{% block content %}
  <section class="container">
    <div class="row justify-content-center">
      <div class="col-lg-9">
	<div class="row mb-3">
	  <div class="col">
	    <h2 class="mx-5 text-center"> {{ gettext("Moderation interface") }}</h2>
	    <hr />
	  </div>
	</div>
	<div class="row">
	  <div class="col">
	    <h3>{{ _("Tags") }}</h3>
	  </div>
	</div>
	<div class="row mb-2">
	  {% if form.tags.entries|length > 0 %}
	    <form method="POST" action="{{ url_for('moderation.tags') }}" class="col">
	      <table class="table">
		<tr>
		  <th>{{ _("Tag name") }}</th>
		</tr>
		{{ form.csrf_token }}
		{% for tag in form.tags.entries %}
		  <tr>
		    {{ tag.form.hidden_tag() }}
		    <td>{{ render_field(tag.form.name, label=False) }}</td>
		  </tr>
		{% endfor %}
	      </table>
	      <div class="row">
		<div class="col">
		  <button type="submit" class="btn btn-block btn-primary">{{ _("Submit") }}</button>
		</div>
	      </div>
	    </form>
	  {% else %}
	    <div class="col">
	      {{ _("There are no entries to be moderated right now.") }}
	    </div>
	  {% endif %}
	</div>
	<div class="row">
	  <div class="col">
	    <a class="btn btn-primary btn-block" href="{{ url_for('moderation.index') }}">{{ _("Return to moderation index.") }}</a>
	  </div>
	</div>
      </div>
    </div>
  </section>
{% endblock %}