editoggia/models/user.py
# models.py ---
#
# Filename: models.py
# Author: Louise <louise>
# Created: Mon May  4 01:45:09 2020 (+0200)
# Last-Updated: Fri Jul 17 03:57:52 2020 (+0200)
#           By: Louise <louise>
#
from datetime import datetime

from flask_babelex import gettext
from flask_login import AnonymousUserMixin, UserMixin

from editoggia.database import db
from editoggia.extensions import bcrypt, lm
from editoggia.models.mixins import CRUDMixin, NameMixin


class RolesUsers(db.Model):
    __tablename__ = "roles_users"

    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(
        "user_id", db.Integer(), db.ForeignKey("user.id"), nullable=False
    )
    role_id = db.Column(
        "role_id", db.Integer(), db.ForeignKey("role.id"), nullable=False
    )


class Role(db.Model, CRUDMixin, NameMixin):
    __tablename__ = "role"

    description = db.Column(db.String(255), nullable=False)

    users = db.relationship(
        "User", secondary="roles_users", lazy="dynamic", back_populates="roles"
    )
    permissions = db.relationship(
        "Permission", secondary="permissions_roles", back_populates="roles"
    )


class PermissionsRoles(db.Model):
    __tablename__ = "permissions_roles"

    id = db.Column(db.Integer(), primary_key=True)
    role_id = db.Column(
        "role_id", db.Integer(), db.ForeignKey("role.id"), nullable=False
    )
    perm_id = db.Column(
        "perm_id", db.Integer(), db.ForeignKey("permission.id"), nullable=False
    )


class Permission(db.Model, CRUDMixin):
    __tablename__ = "permission"

    name = db.Column(db.String(120), unique=True, nullable=False)
    description = db.Column(db.String(255), nullable=False)

    roles = db.relationship(
        "Role", secondary="permissions_roles", back_populates="permissions"
    )


class User(CRUDMixin, UserMixin, db.Model):
    __tablename__ = "user"

    # Basic info
    email = db.Column(db.String(50), unique=True, nullable=False)
    username = db.Column(db.String(50), nullable=False)
    pw_hash = db.Column(db.String(60), nullable=False)

    # More info
    name = db.Column(db.String(128))
    location = db.Column(db.String(128))
    birthdate = db.Column(db.Date())
    gender = db.Column(
        db.Enum(gettext("Woman"), gettext("Man"), gettext("Other"), name="gender_enum")
    )
    bio = db.Column(db.String(500), nullable=False, default="")

    # More profile info
    updated_on = db.Column(
        db.DateTime(), nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow
    )

    # Settings
    language = db.Column(db.String(10), nullable=False, default="")

    # Stories and such
    stories = db.relationship("Story", back_populates="author")
    likes = db.relationship(
        "Story", secondary="user_likes", back_populates="user_likes"
    )
    comments = db.relationship("Comment", back_populates="author")
    history = db.relationship("HistoryView", order_by="desc(HistoryView.date)")
    shelves = db.relationship("Shelf", back_populates="user")

    # Tracking info
    last_active_at = db.Column(db.DateTime())
    last_active_ip = db.Column(db.String(100))
    last_login_at = db.Column(db.DateTime())
    last_login_ip = db.Column(db.String(100))
    login_count = db.Column(db.Integer, default=0)

    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime(), default=datetime.utcnow())

    roles = db.relationship(
        "Role", secondary="roles_users", lazy="dynamic", back_populates="users"
    )

    def __init__(self, password, **kwargs):
        super(User, self).__init__(**kwargs)
        self.set_password(password)

    def __str__(self):
        return self.name if self.name else self.username

    def __repr__(self):
        return "<User #%s:%r>" % (self.id, self.username)

    def set_password(self, password):
        hash_ = bcrypt.generate_password_hash(password, 10).decode("utf-8")
        self.pw_hash = hash_

    def check_password(self, password):
        return bcrypt.check_password_hash(self.pw_hash, password)

    def has_permission(self, permission):
        """
        Check if user has given permission.
        """
        result = self.roles.filter(
            Role.permissions.any(Permission.name == permission)
        ).first()

        return result is not None

    def get_from_history(self, story):
        """
        If user has story in its inventory, return the HistoryView
        object. If not, return None.
        """
        from editoggia.models import HistoryView

        return (
            db.session.query(HistoryView)
            .filter(HistoryView.user_id == self.id)
            .filter(HistoryView.story_id == story.id)
            .first()
        )

    def add_to_history(self, story, chapter_nb=1):
        """
        A user has loaded a story. Update view time, or
        add to history.
        """
        from datetime import datetime

        from editoggia.models import HistoryView

        existing = self.get_from_history(story)

        if existing:
            existing.update(date=datetime.utcnow(), chapter_nb=chapter_nb)
        else:
            # Add a hit to the story
            story.hit()
            HistoryView.create(user_id=self.id, story=story, chapter_nb=chapter_nb)


class UserLikes(db.Model):
    __tablename__ = "user_likes"

    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(
        "user_id", db.Integer(), db.ForeignKey("user.id"), nullable=False
    )
    story_id = db.Column(
        "story_id", db.Integer(), db.ForeignKey("story.id"), nullable=False
    )


class AnonymousUser(AnonymousUserMixin):
    """
    This defines the anonymous user.
    We define this so we can use the same
    functions everywhere for the permission
    system, and the history.
    """

    def has_permission(self, permission):
        return False

    def get_from_history(self, story):
        """
        Because an anonymous user has no history, return None.
        """
        return None

    def add_to_history(self, story, chapter_nb=1):
        """
        Add a hit to the story, an anonymous user has no history.
        """
        story.hit()


lm.anonymous_user = AnonymousUser

editoggia/user/forms.py
# forms.py ---
#
# Filename: forms.py
# Author: Louise <louise>
# Created: Tue May  5 22:09:27 2020 (+0200)
# Last-Updated: Wed Jul  8 11:49:23 2020 (+0200)
#           By: Louise <louise>
#
from flask import current_app
from flask_babelex import Locale, gettext
from flask_wtf import FlaskForm
from wtforms.fields import PasswordField, SelectField, StringField, TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from editoggia.forms.fields import DateField
from editoggia.models import User


class UserForm(FlaskForm):
    username = StringField(
        gettext("Username"),
        validators=[
            DataRequired(message=gettext("Username must be filled.")),
            Length(
                min=2,
                max=50,
                message=gettext("Username must be between 2 and 50 characters."),
            ),
        ],
    )
    email = StringField(
        gettext("Email"),
        validators=[
            Email(message=gettext("Email must be valid.")),
            DataRequired(message=gettext("Email must be filled.")),
            Length(max=128, message=gettext("Email must be less than 128 characters.")),
        ],
    )

    name = StringField(
        gettext("Display name"),
        validators=[
            Length(
                max=128,
                message=gettext("Display name must be less than 128 characters."),
            )
        ],
    )

    def __init__(self, *args, **kwargs):
        FlaskForm.__init__(self, *args, **kwargs)


class SignupUserForm(UserForm):
    password = PasswordField(
        gettext("Password"),
        validators=[
            DataRequired(message=gettext("Password must be filled.")),
            EqualTo("confirm", message=gettext("Passwords must match.")),
            Length(
                min=6,
                max=50,
                message=gettext("Password must be between 6 and 50 characters."),
            ),
        ],
    )
    confirm = PasswordField(
        gettext("Confirm Password"),
        validators=[DataRequired(message=gettext("Password must be confirmed."))],
    )

    def __init__(self, *args, **kwargs):
        UserForm.__init__(self, *args, **kwargs)
        self.user = None

    def validate(self):
        rv = FlaskForm.validate(self)

        if not self.username.data.isalnum():
            self.username.errors.append(
                gettext("Username can only contain " "alphanumerical characters.")
            )
            return False

        # return this after because we might have to add the aforementioned error
        if not rv:
            return False

        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append(gettext("Username already registered."))
            return False

        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append(gettext("Email already registered."))
            return False

        self.user = user
        return True


class EditUserForm(UserForm):
    gender = SelectField(
        gettext("Gender"),
        choices=[
            ("Woman", gettext("Woman")),
            ("Man", gettext("Man")),
            ("Other", gettext("Other")),
            (None, gettext("Doesn't want to say")),
        ],
        # We have to coerce the value to get the None value right
        coerce=lambda x: None if x == "None" else x,
    )

    language = SelectField(gettext("Language"))

    location = StringField()
    birthdate = DateField()
    bio = TextAreaField()

    def populate_language(self):
        """
        Populate the language choices, we have to do it
        here since we need the app context.
        """
        self.language.choices = [
            (lang, Locale.parse(lang).get_display_name(lang))
            for lang in current_app.config["ACCEPTED_LANGUAGES"]
        ]

editoggia/user/__init__.py
# __init__.py ---
#
# Filename: __init__.py
# Author: Louise <louise>
# Created: Mon May  4 01:42:51 2020 (+0200)
# Last-Updated: Thu May 28 15:03:10 2020 (+0200)
#           By: Louise <louise>
#
from flask import Blueprint

user = Blueprint("user", __name__)

import editoggia.user.admin  # noqa
import editoggia.user.views  # noqa

editoggia/user/views.py
# views.py ---
#
# Filename: views.py
# Author: Louise <louise>
# Created: Mon May  4 01:59:58 2020 (+0200)
# Last-Updated: Sat Jul 11 23:18:22 2020 (+0200)
#           By: Louise <louise>
#
from datetime import date, timedelta

from flask import flash, redirect, render_template, url_for
from flask_babelex import gettext
from flask_login import current_user, login_required

from editoggia.bleacher import bleach
from editoggia.database import db
from editoggia.models import User
from editoggia.user import user
from editoggia.user.forms import EditUserForm


def get_profile_info(username):
    user = db.session.query(User).filter(User.username == username).first_or_404()

    # If user is the logged-in one, profile is editable
    editable = user == current_user

    # We have to calculate the age here since it's kinda bothersome
    # to do it in the template.
    age = None
    if user.birthdate:
        age = (date.today() - user.birthdate) // timedelta(days=365.2425)

    return user, editable, age


@user.route("/<username>")
def profile(username):
    """
    Prints the profile of someone.
    This returns the same thing as profile_stories,
    but has a different URL so the default tab can
    be changed easily.
    """
    user, editable, age = get_profile_info(username)

    return render_template(
        "user/profile.jinja2", user=user, age=age, mode="bio", editable=editable
    )


@user.route("/<username>/stories")
def profile_stories(username):
    """
    Prints the profile of someone, with the stories
    tab opened.
    """
    user, editable, age = get_profile_info(username)

    return render_template(
        "user/profile.jinja2", user=user, age=age, mode="stories", editable=editable
    )


@user.route("/<username>/liked")
def profile_liked(username):
    """
    Prints the profile of someone, with the liked
    stories tab opened.
    """
    user, editable, age = get_profile_info(username)

    return render_template(
        "user/profile.jinja2", user=user, age=age, mode="liked", editable=editable
    )


@user.route("/<username>/history")
def profile_history(username):
    """
    Prints the profile of someone, with the history
    tab opened.
    """
    user, editable, age = get_profile_info(username)

    return render_template(
        "user/profile.jinja2", user=user, age=age, mode="history", editable=editable
    )


@user.route("/edit", methods=["GET", "POST"])
@login_required
def edit_profile():
    """
    Edit a user profile.
    """
    form = EditUserForm(obj=current_user)
    form.populate_language()

    if form.validate_on_submit():
        form.bio.process_data(bleach(form.data["bio"]))

        form.populate_obj(current_user)
        current_user.update()

        flash(gettext("Profile edited with success"), "success")
        return redirect(url_for("user.profile", username=current_user.username))
    return render_template("user/edit_profile.jinja2", form=form)

editoggia/templates/user/edit_profile.jinja2
{% from 'components/field.jinja2' import render_field %}
{% extends 'base.jinja2' %}

{% block title %} {{ _("Edit profile") }} {% endblock %}

{% block content %}
  <section class="section">
    <div class="container">
      <div class="row justify-content-center">
	<div class="col-lg-8 text-justified">
	  <h2 class="title text-center"> {{ _("Edit profile") }} </h2>
	  <form action="{{ url_for('user.edit_profile') }}" method="POST">
	    {{ form.csrf_token }}
	    <div class="row">
	      {{ render_field(form.name) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.email) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.birthdate) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.gender, col='col-lg-6') }}
	      {{ render_field(form.language, col='col-lg-6') }}
	    </div>
	    <div class="row">
	      {{ render_field(form.location) }}
	    </div>
	    <div class="row">
	      {{ render_field(form.bio) }}
	    </div>
	    <div class="row pt-2">
	      <div class="form-group col-lg-12">
		<button type="submit" class="btn btn-primary btn-block">{{ _("Submit") }}</button>
	      </div>
	    </div>
	  </form>
	</div>
      </div>
    </div>
  </section>
{% endblock %}

editoggia/templates/user/profile.jinja2
{% from 'components/story_card.jinja2' import render_story_card with context %}
{% extends 'base.jinja2' %}

{% block title %}
  {% if user.name %}
    {{ user.name }} (@{{ user.username }})
  {% else %}
    @{{ user.username }}
  {% endif %}
{% endblock %}

{% block content %}
  <section class="container mt-1" id="main_profile">
    <div class="row">
      <div class="col-lg-3">
	<div class="d-flex align-items-baseline">
	  {% if user.name %}
	    <h2 class="border-bottom">{{ user.name|e }}</h2>
	    <div class="ml-auto text-muted">@{{ user.username|e }}</div>
	  {% else %}
	    <h2 class="border-bottom">@{{ user.username|e }}</h2>
	  {% endif %}
	</div>
	
	{# Location #}
	{% if user.location %}
	  <div id="location">
	    <i class="fas fa-fw fa-compass"></i>
	    {{ user.location|e }}
	  </div>
	{% endif %}

	{# Age #}
	{% if age %}
	  <div id="age">
	    <i class="fas fa-fw fa-birthday-cake"></i>
	    {{ age }} {{ _("years old") }}
	  </div>
	{% endif %}
	
	{# Gender #}
	{% if user.gender == "Woman" %}
	  <i class="fas fa-fw fa-venus"></i>
	  {{ _("Woman") }}
	{% elif user.gender == "Man" %}
	  <i class="fas fa-fw fa-mars"></i>
	  {{ _("Man") }}
	{% elif user.gender == "Other" %}
	  <i class="fas fa-fw fa-genderless"></i>
	  {{ _("Other") }}
	{% endif %}
	
	{% if editable %}
	  <a class="btn btn-primary btn-block" href="{{ url_for('user.edit_profile') }}">
	    <i class="fas fa-fw fa-edit"></i>
	    {{ _("Edit profile") }}
	  </a>
	{% endif %}
      </div>
      <hr class="mt-0"/>
      <div class="col-lg-9">
	<nav class="nav profile-nav">
	  <a class="nav-link {% if mode == 'bio' %}active{% endif %}" href="{{ url_for('user.profile', username=user.username) }}#">
	    {{ _("Biography") }}
	  </a>
	  <a class="nav-link {% if mode == 'stories' %}active{% endif %}" href="{{ url_for('user.profile_stories', username=user.username) }}#">
	    {{ _("Written stories") }}
	  </a>
	  <a class="nav-link {% if mode == 'liked' %}active{% endif %}" href="{{ url_for('user.profile_liked', username=user.username) }}#">
	    {{ _("Liked stories") }}
	  </a>
	  <a class="nav-link {% if mode == 'history' %}active{% endif %}" href="{{ url_for('user.profile_history', username=user.username) }}#">
	    {{ _("History") }}
	  </a>
	</nav>
	<div>
	  {% if mode == 'bio' %}
	    {% if user.bio %}
	      {{ user.bio }}
	    {% else %}
	      <span class="text-muted">{{ _("This user hasn't said anything here…") }}</span>
	    {% endif %}
	  {% endif %}
	  
	  {% if mode == 'stories' %}
	    {% for story in user.stories %}
	      {{ render_story_card(story) }}
	    {% endfor %}
	  {% endif %}

	  {% if mode == 'liked' %}
	    {% for story in user.likes %}
	      {{ render_story_card(story) }}
	    {% endfor %}
	  {% endif %}

	  {% if mode == 'history' %}
	    {% for history_view in user.history %}
	      {{ render_story_card(history_view.story) }}
	    {% endfor %}
	  {% endif %}
	</div>
      </div>
  </section>
{% endblock %}